#!/usr/bin/env bash -eoux pipefail

build_capacitor_simulator() {
	xcodebuild archive \
		-scheme Capacitor \
		-workspace Capacitor.xcworkspace \
		-destination "generic/platform=iOS Simulator" \
		-configuration Debug \
		-archivePath ./Build/iOS-Simulator \
		SKIP_INSTALL=NO \
		BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
		DEBUG_INFORMATION_FORMAT="dwarf-with-dsym"
}

build_capacitor_ios() {
	xcodebuild archive \
		-scheme Capacitor \
		-workspace Capacitor.xcworkspace \
		-destination "generic/platform=iOS" \
		-archivePath ./Build/iOS \
		SKIP_INSTALL=NO \
		SWIFT_SERIALIZE_DEBUGGING_OPTIONS=NO \
		DEBUG_INFORMATION_FORMAT="dwarf-with-dsym" \
		BUILD_LIBRARY_FOR_DISTRIBUTION=YES
}

create_cordova_scheme() {
	mkdir -p ../CapacitorCordova/CapacitorCordova.xcodeproj/xcshareddata/xcschemes
	cat <<'SCHEME' > ../CapacitorCordova/CapacitorCordova.xcodeproj/xcshareddata/xcschemes/Cordova.xcscheme
<?xml version="1.0" encoding="UTF-8"?>
<Scheme LastUpgradeVersion="1500" version="1.7">
   <BuildAction parallelizeBuildables="YES" buildImplicitDependencies="YES">
      <BuildActionEntries>
         <BuildActionEntry buildForArchiving="YES">
            <BuildableReference
               BuildableIdentifier="primary"
               BlueprintIdentifier="2F5C86DB1FE94845004B09C7"
               BuildableName="Cordova.framework"
               BlueprintName="Cordova"
               ReferencedContainer="container:CapacitorCordova.xcodeproj">
            </BuildableReference>
         </BuildActionEntry>
      </BuildActionEntries>
   </BuildAction>
   <ArchiveAction buildConfiguration="Release" revealArchiveInOrganizer="YES"/>
</Scheme>
SCHEME
}

build_cordova_simulator() {
	xcodebuild archive \
		-scheme Cordova \
		-project ../CapacitorCordova/CapacitorCordova.xcodeproj \
		-destination "generic/platform=iOS Simulator" \
		-configuration Debug \
		-archivePath ./Build/iOS-Simulator-Cordova \
		SKIP_INSTALL=NO \
		BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
		DEBUG_INFORMATION_FORMAT="dwarf-with-dsym"
}

build_cordova_ios() {
	xcodebuild archive \
		-scheme Cordova \
		-project ../CapacitorCordova/CapacitorCordova.xcodeproj \
		-destination "generic/platform=iOS" \
		-archivePath ./Build/iOS-Cordova \
		SKIP_INSTALL=NO \
		SWIFT_SERIALIZE_DEBUGGING_OPTIONS=NO \
		DEBUG_INFORMATION_FORMAT="dwarf-with-dsym" \
		BUILD_LIBRARY_FOR_DISTRIBUTION=YES
}

create_xcframeworks() {
	build_capacitor_simulator
	build_capacitor_ios
	build_cordova_simulator
	build_cordova_ios

	rm -rf ./Build/iOS-Simulator.xcarchive/Products/Library/Frameworks/Capacitor.framework/Frameworks
	rm -rf ./Build/iOS.xcarchive/Products/Library/Frameworks/Capacitor.framework/Frameworks

	xcodebuild -create-xcframework \
		-framework ./Build/iOS-Simulator.xcarchive/Products/Library/Frameworks/Capacitor.framework \
		-debug-symbols $PWD/Build/iOS-Simulator.xcarchive/dSYMs/Capacitor.framework.dSYM \
		-framework ./Build/iOS.xcarchive/Products/Library/Frameworks/Capacitor.framework \
		-debug-symbols $PWD/Build/iOS.xcarchive/dSYMs/Capacitor.framework.dSYM \
		-output Capacitor.xcframework

	xcodebuild -create-xcframework \
		-framework ./Build/iOS-Simulator-Cordova.xcarchive/Products/Library/Frameworks/Cordova.framework \
		-debug-symbols $PWD/Build/iOS-Simulator-Cordova.xcarchive/dSYMs/Cordova.framework.dSYM \
		-framework ./Build/iOS-Cordova.xcarchive/Products/Library/Frameworks/Cordova.framework \
		-debug-symbols $PWD/Build/iOS-Cordova.xcarchive/dSYMs/Cordova.framework.dSYM \
		-output Cordova.xcframework

}

CAPACITOR_REF="${2:-$1}"

git clone https://github.com/ionic-team/capacitor capacitor-checkout
cd capacitor-checkout/ios/Capacitor
git checkout $CAPACITOR_REF

create_cordova_scheme
create_xcframeworks

mv Capacitor.xcframework ../../../
mv Cordova.xcframework ../../../
